export const categoryList = [
    {
        id: 1,
        value: 'Girls',
        label: '👧Girls',
    },
    {
        id: 2,
        value: 'Boys',
        label: '👦Boys',
    },
];

export const ratingList = [
    {
        id : 1,
        value : '1',
        label : '1⭐',
    },
    {
        id : 2,
        value : '2',
        label : '2⭐',
    },
    {
        id : 3,
        value : '3',
        label : '3⭐',
    },
    {
        id : 4,
        value : '4',
        label : '4⭐',
    },
    {
        id : 5,
        value : '5',
        label : '5⭐',
    },
];

export const dataList = [
    {
        id: 1,
        title: 'Stanza Living',
        distfromcollege: '500m',
        category: 'Boys',
        amenities:'Laundry',
        rating: 5,
        price: 2500,
        coverSrc: '/images/img1.png',
    },
    {
        id: 2,
        title: 'Door urban',
        distfromcollege: '1km',
        category: 'Girls',
        amenities: 'Mess',
        rating: 4,
        price: 1000,
        coverSrc: '/images/img2.png',
      },
      {
        id: 3,
        title: 'Pine hostel',
        distfromcollege: '120m',
        category: 'Girls',
        amenities: 'TV, Laundry',
        rating: 3,
        price: 2000,
        coverSrc: '/images/img3.png',
      },
      {
        id: 4,
        title: 'Wharf hostel',
        distfromcollege: '80m',
        category: 'Boys',
        amenities: 'Mess, Laundry',
        rating: 4,
        price: 4000,
        coverSrc: '/images/img4.png',
      },
      {
        id: 5,
        title: 'ABC hostel',
        distfromcollege: '280m',
        category: 'Girls',
        amenities: 'Mess',
        rating: 5,
        price: 2900,
        coverSrc: '/images/img5.png',
      },
      {
        id: 6,
        title: 'XYZ hostel',
        distfromcollege: '300m',
        category: 'Boys',
        amenities: 'Mess, Laundry',
        rating: 2,
        price: 2000,
        coverSrc: '/images/img6.jpg',
      },
      {
        id: 7,
        title: 'Gurukrupa hostel',
        distfromcollege: '50m',
        category: 'Girls',
        amenities: 'Mess, Laundry',
        rating: 4,
        price: 3800,
        coverSrc: '/images/img7.jpg',
      },
      {
        id: 8,
        title: 'Stanza Living',
        distfromcollege: '100m',
        category: 'Girls',
        amenities: 'Mess, Laundry',
        rating: 5,
        price: 2500,
        coverSrc: '/images/img8.jpg',
      },
      {
        id: 9,
        title: 'Krushnai hostel',
        distfromcollege: '400m',
        category: 'Boys',
        amenities: 'Mess',
        rating: 4,
        price: 2750,
        coverSrc: '/images/img9.jpg',
      },
      {
        id: 10,
        title: 'Happy hostel',
        distfromcollege: '200m',
        category: 'Girls',
        amenities: 'Mess,',
        rating: 3,
        price: 3000,
        coverSrc: '/images/img10.jpg',
      },
      {
        id: 11,
        title: 'Krushnai hostel',
        distfromcollege: '400m',
        category: 'Boys',
        amenities: 'Mess',
        rating: 4,
        price: 2750,
        coverSrc: '/images/img11.jpg',
      },
      {
        id: 12,
        title: 'PICT hostel',
        distfromcollege: '40m',
        category: 'Boys',
        amenities: 'Mess',
        rating: 4,
        price: 2750,
        coverSrc: '/images/img12.jpg',
      },
      {
        id: 13,
        title: 'PICT hostel',
        distfromcollege: '40m',
        category: 'Girls',
        amenities: 'Mess',
        rating: 4,
        price: 2750,
        coverSrc: '/images/img13.jpg',
      },
      {
        id: 14,
        title: 'Durga hostel',
        distfromcollege: '400m',
        category: 'Girls',
        amenities: 'Mess',
        rating: 2,
        price: 1700,
        coverSrc: '/images/img14.jpg',
      },
      {
        id: 15,
        title: 'Swarup hostel',
        distfromcollege: '400m',
        category: 'Boys',
        amenities: 'Mess',
        rating: 4,
        price: 3800,
        coverSrc: '/images/img15.jpg',
      },
    ];